reeler/src/main/java/com/hkstlr/reeler/weblogger/users/boundary/login/LoginBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hkstlr.reeler.weblogger.users.boundary.login;

import com.hkstlr.reeler.app.control.WebloggerException;
import com.hkstlr.reeler.weblogger.weblogs.control.URLStrategy;
import com.hkstlr.reeler.weblogger.users.boundary.manager.UserManager;
import com.hkstlr.reeler.weblogger.users.control.PasswordDigester;
import com.hkstlr.reeler.weblogger.users.entities.User;
import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.ManagedBean;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;


import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.NoResultException;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

/**
 *
 * @author henry.kastler
 */
@ManagedBean
@RequestScoped
@Named
public class LoginBean implements Serializable {

    private String username;
    private String password;

    public static final String USER_SESSION_KEY = "user";

    @EJB
    private transient UserManager userManager;    

    
    private transient URLStrategy urlStrategy;

    
    private static final Logger log = Logger.getLogger(LoginBean.class.getName());


    /**
     * Creates a new instance of LoginBean
     * @param userManager
     * @param urlStrategy
     */
    
    @Inject 
    public LoginBean(URLStrategy urlStrategy) {
        this.urlStrategy = urlStrategy;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * <p>
     * Validates the user. If the user doesn't exist or the password is
     * incorrect, the appropriate message is added to the current
     * <code>FacesContext</code>. If the user successfully authenticates,
     * navigate them to the page referenced by the outcome
     * <code>app-main</code>.
     * </p>
     *
     */
    public void validateUser() throws WebloggerException {
        FacesContext context = FacesContext.getCurrentInstance();
        User user = getUser();
       

        String hashPwd = password;
        
        try {
            hashPwd = PasswordDigester.getDigestedPassword(password);
        } catch (Exception ex) {
            
            log.log(Level.SEVERE, null, ex);
        }

        if ((user != null && user.getPassword().equals(hashPwd))) {
            context.getExternalContext().getSessionMap().put(USER_SESSION_KEY, user);

            HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();
            
            if (request.getUserPrincipal() != null) {
                try {
                    request.logout();
                } catch (ServletException ex) {
                    Logger.getLogger(LoginBean.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            String outcome = "/weblogger/login/index";
            
            try {
                request.login(this.username, this.password);
                
                outcome = urlStrategy.getLoginSuccessOutcome(user); // Do your thing?
            } catch (ServletException e) {
                log.log(Level.SEVERE,"user not realm authenticated:",e);
                context.addMessage(null, new FacesMessage("Login failed." + e.getMessage()));
                
            }

            log.log(Level.INFO,"user:" + user.toJsonString());
            log.log(Level.INFO, "user?{0}", request.isUserInRole("user"));
            log.log(Level.INFO, "admin?{0}", request.isUserInRole("admin"));

            FacesContext facesContext = FacesContext.getCurrentInstance();
            
            facesContext.getApplication().getNavigationHandler().handleNavigation(facesContext, null, outcome);

        } else {
            FacesMessage message;
            if (user != null) {
                message = new FacesMessage(FacesMessage.SEVERITY_ERROR,
                        "Login Failed!",
                        "Username '"
                                + username
                                + "' supplied wrong password.");
            } else {
                message = new FacesMessage(FacesMessage.SEVERITY_ERROR,
                        "Login Failed!",
                        "Username '"
                                + username
                                + "' does not exist.");
            }
            context.addMessage(null, message);
            
        }
    }

    private User getUser() {
        User userToGet = null;
        try {
            userToGet = userManager.getUserByUserName(username);
            Logger.getLogger(LoginBean.class.getName()).log(Level.INFO, "user:{0}", userToGet.toJsonString());
            return userToGet;

        } catch (NoResultException |  NullPointerException ex) {

            Logger.getLogger(LoginBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return userToGet;
    }

    /**
     * <p>
     * When invoked, it will invalidate the user's session and move them to the
     * homepage.</p>
     *
     * @return <code>home</code>
     */
    public String logout() {
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);
        if (session != null) {
            session.invalidate();
        }
        
        return "/index?faces-redirect=true";

    }

}

reeler/src/main/java/com/hkstlr/reeler/weblogger/weblogs/boundary/jsf/reelerui/ReelerUIBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hkstlr.reeler.weblogger.weblogs.boundary.jsf.reelerui;

import com.hkstlr.reeler.app.control.WebloggerException;
import com.hkstlr.reeler.weblogger.weblogs.boundary.Weblogger;
import com.hkstlr.reeler.weblogger.weblogs.entities.Weblog;
import com.hkstlr.reeler.weblogger.weblogs.entities.WeblogPermission;
import com.hkstlr.reeler.weblogger.users.entities.User;
import com.hkstlr.reeler.weblogger.users.entities.UserRole;
import com.hkstlr.reeler.weblogger.weblogs.entities.WeblogBookmarkFolder;
import java.io.IOException;
import java.io.Serializable;
import java.security.Permission;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;

import javax.faces.bean.SessionScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

/**
 *
 * @author henry.kastler
 */
@ManagedBean(name = "reelerUiBean")
@SessionScoped
public class ReelerUIBean implements Serializable {

    private static final transient Logger LOG = Logger.getLogger(ReelerUIBean.class.getName());

    @EJB
    private transient Weblogger weblogger;

    private User user;

    private List<Weblog> userWeblogs;

    private Map<String, String> userWeblogPermissions;

    private Map<String, String> pages = new LinkedHashMap<>();

    private static final String PAGE_HOME = "/weblogger/reeler-ui";

    private static final String PATH = PAGE_HOME + "/weblog";

    private Weblog currentWeblog = new Weblog();

    public ReelerUIBean() {
        //default constructor
    }

    @PostConstruct
    public void init() {
        setUserFromSession();
        LOG.log(Level.INFO, "expected that a session bean would init only once");
        pages.put("entry", "Create Entry");
        pages.put("entries", "Entries");
        pages.put("comments", "Comments");
        pages.put("categories", "Categories");
        pages.put("blogrolls", "Blogrolls");
        pages.put("mediafiles", "Media Files");
    }

    /**
     * Get the value of user
     *
     * @return the value of user
     */
    public User getUser() {
        return user;
    }

    public List<UserRole> getUserRolesAsList(Set<UserRole> roles) {
        return new ArrayList<>(roles);
    }

    public Map<String, String> getUserWeblogPermissions() {
        return userWeblogPermissions;
    }

    public List<Weblog> getUserWeblogs() {
        return userWeblogs;
    }

    public void setUserWeblogs(User user) {

        List<Weblog> ublogs = null;
        List<Weblog> finalUblogs = new ArrayList<>();
        try {

            ublogs = weblogger.getWeblogManager().getUserWeblogs(user, true);
        } catch (WebloggerException ex) {
            LOG.log(Level.SEVERE, null, ex);
        }
        if (ublogs == null) {
            ublogs = new ArrayList<>();
        }
        for (Weblog blog : ublogs) {
            
            finalUblogs.add(blog);
            //refresh the current weblog
            if (currentWeblog != null && blog.equals(currentWeblog)) {
                currentWeblog = blog;                
            }
        }
        this.userWeblogs = null;
        this.userWeblogs = finalUblogs;
    }

    public void setUserWeblogs() {
        setUserWeblogs(this.user);
    }

    public void setWeblogPermissions() {

        Map<String, String> weblogPermissionMap = new HashMap<>();

        for (Permission perm : user.getPermissions()) {
            
            if(perm instanceof WeblogPermission){
                WeblogPermission wp = (WeblogPermission) perm;
                
                weblogPermissionMap.put(wp.getObjectId(), wp.getActions());
            }
        }

        this.userWeblogPermissions = weblogPermissionMap;
    }

    

    /**
     * Set the value of user
     *
     * @param user new value of user
     */
    public void setUser(User user) {
        this.user = user;
    }

    public void setUserFromSession() {
        this.user = (User) FacesContext.getCurrentInstance().getExternalContext().getSessionMap().get("user");
        
    }

    public String getPath() {
        return PATH;
    }

    public Weblog getCurrentWeblog() {
        return currentWeblog;
    }

    public void setCurrentWeblog(Weblog currentWeblog) {
        this.currentWeblog = currentWeblog;
    }

    public Map<String, String> getPages() {
        return pages;
    }

    public void setPages(Map<String, String> pages) {
        this.pages = pages;
    }

    public String getPageHome() {
        return PAGE_HOME;
    }

    public void action(Weblog weblog, String page) throws WebloggerException {
        LOG.finer("setting weblog and redirecting...");
        this.currentWeblog = weblog;
        ExternalContext context = FacesContext.getCurrentInstance().getExternalContext();
        try {
            StringBuilder actionPath = new StringBuilder(context.getRequestContextPath());
            actionPath.append(ReelerUIBean.PATH).append("/");
            if ("config".equals(page)) {
                actionPath.append("settings/");
            }
            actionPath.append(page).append(".xhtml");
            context.redirect(actionPath.toString());
        } catch (IOException ex) {
            LOG.log(Level.SEVERE,"action error",ex);
            
        }
    }

    public void newWeblog() throws WebloggerException {

        this.currentWeblog = new Weblog();
        ExternalContext context = FacesContext.getCurrentInstance().getExternalContext();
        try {
            StringBuilder createPath = new StringBuilder(context.getRequestContextPath());
            createPath.append(ReelerUIBean.PATH);
            createPath.append("/create.xhtml");
            context.redirect(createPath.toString());
        } catch (IOException ex) {
            LOG.log(Level.SEVERE,"newWeblog",ex);
        }
    }

    public void indexViewAction() {
        try {
            setUserWeblogs();
        } catch (Exception e) {
            LOG.log(Level.SEVERE,null,e);
        }
        setWeblogPermissions();
    }

    public void blogrollsViewAction() {
        setUserWeblogs();
        setWeblogPermissions();
       
        List<WeblogBookmarkFolder> folders = weblogger.getWeblogBookmarkManager().getBookmarkFoldersForWeblog(currentWeblog);
        LOG.finer("numberOfFolders:" + folders.size());
        
        this.currentWeblog.setBookmarkFolders(folders);
        LOG.finer("currentWeblog.numberOfFolders:" + this.currentWeblog.getBookmarkFolders().size());
    }

}

reeler/src/main/java/com/hkstlr/reeler/weblogger/weblogs/boundary/jsf/reelerui/admin/AdminUIBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hkstlr.reeler.weblogger.weblogs.boundary.jsf.reelerui.admin;

import java.util.LinkedHashMap;
import java.util.Map;
import javax.annotation.PostConstruct;
import javax.annotation.security.RolesAllowed;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;

/**
 *
 * @author henry.kastler
 */
@RolesAllowed("admin")
@ManagedBean
@RequestScoped
public class AdminUIBean {
    
    private Map<String, String[]> pages = new LinkedHashMap<>();

    private static final String PATH = "/weblogger/reeler-ui/admin";
    
    private static final String template = "/WEB-INF/weblogger/templates/reeler-ui/pageContentTemplate.xhtml";
    
    @ManagedProperty(value="#{param.page}")
    private String page;

    public AdminUIBean() {
        //default constructor
    }
    
    @PostConstruct
    public void init(){
        if(page == null){
            page = "index";
        }
        pages.put("index", new String[]{"label_configuration","label_serveradmin"});        
        pages.put("users", new String[]{"label_useradmin"});        
        pages.put("comments", new String[]{"label_globalcomment"});        
        pages.put("pings", new String[]{"label_pings"});        
        pages.put("cacheinfo", new String[]{"label_cacheinfo"});        
    }

    public Map<String, String[]> getPages() {
        return pages;
    }

    public void setPages(Map<String, String[]> pages) {
        this.pages = pages;
    }

    public String getPath() {
        return PATH;
    }

    public String getPage() {
        return page;
    }

    public void setPage(String page) {
        this.page = page;
    }

    public String getTemplate() {
        return template;
    }
    
    public void viewAction(String page){
        this.page = page;
    }
    
}

reeler/src/main/java/com/hkstlr/reeler/weblogger/weblogs/boundary/jsf/reelerui/weblog/AuthorBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hkstlr.reeler.weblogger.weblogs.boundary.jsf.reelerui.weblog;

import com.hkstlr.reeler.weblogger.weblogs.boundary.Weblogger;
import com.hkstlr.reeler.weblogger.weblogs.boundary.jsf.reelerui.ReelerUIBean;
import javax.ejb.EJB;
import javax.faces.bean.ManagedProperty;

/**
 *
 * @author henry.kastler
 */
public abstract class AuthorBean<T> {
    
    private Class<T> entityClass;
    
    @EJB
    Weblogger weblogger;
    
    @ManagedProperty(value = "#{reelerUiBean}")
    ReelerUIBean reelerUiBean;
    
    @ManagedProperty(value = "#{param.id}")
    protected String id;
    
    @ManagedProperty(value = "#{param.action}")
    protected String action;
    
    protected String actionLabel;

    public AuthorBean() {
        //default constructor
    }
    
    public AuthorBean(Class<T> entityClass){
        this.entityClass = entityClass;
    }
    
   

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getAction() {
        return action;
    }

    public void setAction(String action) {
        this.action = action;
    }

    public String getActionLabel() {
        return actionLabel;
    }

    public void setActionLabel(String actionLabel) {
        this.actionLabel = actionLabel;
    }

    public Weblogger getWeblogger() {
        return weblogger;
    }

    public void setWeblogger(Weblogger weblogger) {
        this.weblogger = weblogger;
    }

    public ReelerUIBean getReelerUiBean() {
        return reelerUiBean;
    }

    public void setReelerUiBean(ReelerUIBean reelerUiBean) {
        this.reelerUiBean = reelerUiBean;
    }
    
    public void setActionLabel(){
        if("create".equals(action)){
            actionLabel = "Create";
        }else if("edit".equals(action)){
            actionLabel = "Edit";
        }
    }
       
    
    
}

reeler/src/main/webapp/weblogger/reeler-ui/admin/cacheinfo.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="#{adminUIBean.template}"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:jsf="http://xmlns.jcp.org/jsf">
    <ui:param name="pageBean" value="#{adminUIBean}"/>
    <f:metadata>    
        <f:viewAction action="#{adminUIBean.viewAction('cacheinfo')}"/>              
    </f:metadata> 

    <ui:define name="pageContent">
        <form jsfc="h:form">

            <input type="hidden" name="page" value="cacheinfo"/>
            <h:commandButton class="btn btn-primary"
                             id="updateCacheInfo" 
                             value="#{messages.label_update} #{messages[adminUIBean.pages[adminUIBean.page][0]]}"
                             action="#{userAdminBean.updateUser()}"/>
            <input 
                jsf:id="cancelButton"
                type="button" 
                class="btn btn-secondary"
                value="Cancel" 
                onclick="window.location = '#{request.contextPath}#{reelerUiBean.path}'"/>
        </form>
    </ui:define>   

</ui:composition>

reeler/src/main/webapp/weblogger/reeler-ui/admin/comments.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="#{adminUIBean.template}"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:jsf="http://xmlns.jcp.org/jsf">
    <ui:param name="pageBean" value="#{adminUIBean}"/>
    <f:metadata>    
        <f:viewAction action="#{adminUIBean.viewAction('comments')}"/>              
    </f:metadata> 

    <ui:define name="pageContent">
        <form jsfc="h:form">
            <input type="hidden" jsf:id="page" value="#{adminUIBean.page}"/>
            <h:commandButton class="btn btn-primary"
                             id="updateComments" 
                             value="#{messages.label_update} #{messages[adminUIBean.pages[adminUIBean.page][0]]}"
                             action="#{userAdminBean.updateUser()}"/>
            <input 
                jsf:id="cancelButton"
                type="button" 
                class="btn btn-secondary"
                value="Cancel" 
                onclick="window.location = '#{request.contextPath}#{reelerUiBean.path}'"/>
        </form>
    </ui:define>   

</ui:composition>

reeler/src/main/webapp/weblogger/reeler-ui/admin/index.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="#{adminUIBean.template}"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:jsf="http://xmlns.jcp.org/jsf">

    <ui:param name="pageBean" value="#{adminUIBean}"/>
    <f:metadata>        
        <f:viewAction action="#{adminUIBean.viewAction('index')}"/>              
    </f:metadata> 

    <ui:define name="pageContent">
        <form id="globalConfig" name="globalConfig" jsfc="h:form">
            <ui:repeat value="#{runtimeConfigBean.runtimeConfigDefs.configDefs}"
                       var="configDef">
                <ui:repeat value="#{configDef.displayGroups}" var="displayGroup">                    
                    <h3>#{runtimeConfigBean.res.getString(displayGroup.key)}</h3>
                    <br/>
                    <ui:repeat value="#{displayGroup.propertyDefs}" var="propertyDef">
                        <div class="form-group" jsf:id="text" rendered="#{propertyDef.type eq 'string' 
                                                                          or propertyDef.type eq 'text'}">
                            <label for="#{propertyDef.name}" class="control-label">
                                #{runtimeConfigBean.res.getString(propertyDef.key)}
                            </label>
                            <input 
                                jsfc="h:inputText"
                                type="text" 
                                name="#{propertyDef.name}" 
                                value="#{runtimeConfigBean.runtimeConfigs[propertyDef.name]}"
                                class="form-control" 
                                rendered="#{propertyDef.type eq 'string'}"/>

                            <textarea 
                                class="form-control"
                                jsfc="h:inputTextarea"
                                name="#{propertyDef.name}"
                                value="#{runtimeConfigBean.runtimeConfigs[propertyDef.name]}"
                                rendered="#{propertyDef.type eq 'text'}">
                            </textarea>
                        </div> 
                        <div class="checkbox" jsf:id="checkbox" rendered="#{propertyDef.type eq 'boolean'}">
                            <label jsf:for="checkbox">
                                <input jsfc="h:selectBooleanCheckbox"
                                       type="checkbox"
                                       value="#{runtimeConfigBean.runtimeConfigs[propertyDef.name]}"
                                       name="#{propertyDef.name}"
                                       rendered="#{propertyDef.type eq 'boolean'}"/>
                                <h:outputText value="#{runtimeConfigBean.res.getString(propertyDef.key)}"/>
                            </label>
                        </div>
                    </ui:repeat>
                    <hr/>
                </ui:repeat>
                <hr/>
            </ui:repeat>
            <input type="hidden" jsf:id="page" value="#{adminUIBean.page}"/>
            <h:commandButton id="updateRuntimeConfig" 
                             value="#{messages.label_update} #{messages[adminUIBean.pages[adminUIBean.page][0]]}"
                             action="#{runtimeConfigBean.updateConfigs()}"
                             styleClass="btn btn-primary">
            </h:commandButton>
            <input 
                jsf:id="cancelButton"
                type="button" 
                class="btn btn-secondary"
                value="Cancel" 
                onclick="window.location = '#{request.contextPath}#{reelerUiBean.path}'"/>
        </form>
    </ui:define>

</ui:composition>

reeler/src/main/webapp/weblogger/reeler-ui/admin/pings.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="#{adminUIBean.template}"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:jsf="http://xmlns.jcp.org/jsf">
        <ui:param name="pageBean" value="#{adminUIBean}"/>        
        <f:metadata>    
            <f:viewAction action="#{adminUIBean.viewAction('pings')}"/>              
        </f:metadata> 
        
        <ui:define name="pageContent">
            <form jsfc="h:form">
                <input type="hidden" name="page" value="pings"/>
               <h:commandButton class="btn btn-primary"
                             id="updatePings" 
                             value="#{messages.label_update} #{messages[adminUIBean.pages[adminUIBean.page][0]]}"
                             action="#{userAdminBean.updateUser()}"/>
            <input 
                jsf:id="cancelButton"
                type="button" 
                class="btn btn-secondary"
                value="Cancel" 
                onclick="window.location = '#{request.contextPath}#{reelerUiBean.path}'"/>
            </form>
        </ui:define>   
    
</ui:composition>

reeler/src/main/webapp/weblogger/reeler-ui/admin/user-profile.xhtml
<ui:composition template="/WEB-INF/weblogger/templates/reeler-ui/pageContentTemplate.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:jsf="http://xmlns.jcp.org/jsf">

    <ui:define name="title">
        <h:outputText value="#{userAdminBean.actionLabel} User"></h:outputText>            
    </ui:define>

    <ui:define name="head">

    </ui:define>

    <ui:define name="navigation">

    </ui:define>
    <ui:define name="content">
        <f:view>
            <ui:include src="/weblogger/reeler-ui/user/profile/profile-form.xhtml">
                <ui:param name="formTitle" value="#{userAdminBean.actionLabel} User"/>
                <ui:param name="bean" value="#{userAdminBean}"/>
                <ui:param name="isAdmin" value="#{true}"/>
            </ui:include>
        </f:view>
    </ui:define>
    <ui:define name="sideNav">

    </ui:define>

    <ui:define name="postBody">

    </ui:define>

</ui:composition>

reeler/src/main/webapp/weblogger/reeler-ui/admin/users.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="#{adminUIBean.template}"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:jsf="http://xmlns.jcp.org/jsf">

    <ui:param name="pageBean" value="#{adminUIBean}"/>
    <f:metadata>    
        <f:viewAction action="#{adminUIBean.viewAction('users')}"/>              
    </f:metadata> 

    <ui:define name="pageContent">
        <div><h3>Select user to administer</h3>
            <p>Select user and click edit button to edit the user's profile and the user's weblogs.</p>
        </div>
        <form method="get" action="user-profile.xhtml">
            <select
                class="form-control"
                name="id"
                size="10">
                <ui:repeat value="#{userAdminBean.getUsers()}"
                           var="user">
                    <option value="#{user.id}">
                        #{user.userName}(#{user.emailAddress})
                    </option>
                </ui:repeat>
            </select>


            <input type="hidden" name="action" value="edit"/>
            <input
                type="submit"
                class="btn btn-primary"
                             id="updateUsers" 
                             value="Edit User"/>
            <input 
                jsf:id="cancelButton"
                type="button" 
                class="btn btn-secondary"
                value="Cancel" 
                onclick="window.location = '#{request.contextPath}#{reelerUiBean.pageHome}'"/>
        </form>
        <div><h3>New user creation</h3></div>
        <div>
            <span class="help-block">
                Or you can <a href="#{request.contextPath}#{reelerUiBean.pageHome}/admin/user-profile.xhtml">create a new user</a>
            </span>
        </div>
    </ui:define>   

</ui:composition>