reeler/src/main/java/com/hkstlr/reeler/weblogger/users/entities/JdbcrealmGroup.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hkstlr.reeler.weblogger.users.entities;

import com.hkstlr.reeler.app.control.JsonBuilder;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.json.JsonObject;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author henry.kastler
 */
@Entity
@Table(name = "jdbcrealm_group")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "JdbcrealmGroup.findAll", query = "SELECT j FROM JdbcrealmGroup j"),
    @NamedQuery(name = "JdbcrealmGroup.findByJdbcrealmGroupId", query = "SELECT j FROM JdbcrealmGroup j WHERE j.jdbcrealmGroupId = :jdbcrealmGroupId"),
    @NamedQuery(name = "JdbcrealmGroup.findByGroupname", query = "SELECT j FROM JdbcrealmGroup j WHERE j.groupname = :groupname")})
public class JdbcrealmGroup implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "jdbcrealm_groupid")
    private Integer jdbcrealmGroupId;
    
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 255)
    @Column(name = "groupname")
    private String groupname;
    
    @ManyToMany(mappedBy = "jdbcrealmGroups")
    private List<User> users = new ArrayList<User>();
    
    
    public JdbcrealmGroup() {
        //constructor
    }

    public JdbcrealmGroup(Integer jdbcrealmGroupId) {
        this.jdbcrealmGroupId = jdbcrealmGroupId;
    }

    public JdbcrealmGroup(Integer jdbcrealmGroupId, String groupname) {
        this.jdbcrealmGroupId = jdbcrealmGroupId;
        this.groupname = groupname;
    }

    public Integer getJdbcrealmGroupId() {
        return jdbcrealmGroupId;
    }

    public void setJdbcrealmGroupId(Integer jdbcrealmGroupId) {
        this.jdbcrealmGroupId = jdbcrealmGroupId;
    }

    public String getGroupname() {
        return groupname;
    }

    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }

        
    
    
    @Override
    public int hashCode() {
        int hash = 0;
        hash += (jdbcrealmGroupId != null ? jdbcrealmGroupId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof JdbcrealmGroup)) {
            return false;
        }
        JdbcrealmGroup other = (JdbcrealmGroup) object;
        if ((this.jdbcrealmGroupId == null && other.jdbcrealmGroupId != null) || (this.jdbcrealmGroupId != null && !this.jdbcrealmGroupId.equals(other.jdbcrealmGroupId))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        //skip the manytomany with the owner or jsonbuilder will stackoverflow
        return new JsonBuilder().toJsonString(this,new String[]{"users"});
    }
    
     
    public JsonObject toJsonObject() {
        //skip the manytomany with the owner or jsonbuilder will stackoverflow
        return new JsonBuilder().toJsonObject(this,new String[]{"users"});
    }
    
}

reeler/src/main/java/com/hkstlr/reeler/weblogger/users/boundary/login/LoginBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hkstlr.reeler.weblogger.users.boundary.login;

import com.hkstlr.reeler.app.control.WebloggerException;
import com.hkstlr.reeler.weblogger.weblogs.control.URLStrategy;
import com.hkstlr.reeler.weblogger.users.boundary.manager.UserManager;
import com.hkstlr.reeler.weblogger.users.control.PasswordDigester;
import com.hkstlr.reeler.weblogger.users.entities.User;
import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.ManagedBean;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;


import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.NoResultException;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

/**
 *
 * @author henry.kastler
 */
@ManagedBean
@RequestScoped
@Named
public class LoginBean implements Serializable {

    private String username;
    private String password;

    public static final String USER_SESSION_KEY = "user";

    @EJB
    private transient UserManager userManager;    

    
    private transient URLStrategy urlStrategy;

    
    private static final Logger log = Logger.getLogger(LoginBean.class.getName());


    /**
     * Creates a new instance of LoginBean
     * @param userManager
     * @param urlStrategy
     */
    
    @Inject 
    public LoginBean(URLStrategy urlStrategy) {
        this.urlStrategy = urlStrategy;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * <p>
     * Validates the user. If the user doesn't exist or the password is
     * incorrect, the appropriate message is added to the current
     * <code>FacesContext</code>. If the user successfully authenticates,
     * navigate them to the page referenced by the outcome
     * <code>app-main</code>.
     * </p>
     *
     */
    public void validateUser() throws WebloggerException {
        FacesContext context = FacesContext.getCurrentInstance();
        User user = getUser();
       

        String hashPwd = password;
        
        try {
            hashPwd = PasswordDigester.getDigestedPassword(password);
        } catch (Exception ex) {
            
            log.log(Level.SEVERE, null, ex);
        }

        if ((user != null && user.getPassword().equals(hashPwd))) {
            context.getExternalContext().getSessionMap().put(USER_SESSION_KEY, user);

            HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();
            
            if (request.getUserPrincipal() != null) {
                try {
                    request.logout();
                } catch (ServletException ex) {
                    Logger.getLogger(LoginBean.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            String outcome = "/weblogger/login/index";
            
            try {
                request.login(this.username, this.password);
                
                outcome = urlStrategy.getLoginSuccessOutcome(user); // Do your thing?
            } catch (ServletException e) {
                log.log(Level.SEVERE,"user not realm authenticated:",e);
                context.addMessage(null, new FacesMessage("Login failed." + e.getMessage()));
                
            }

            log.log(Level.INFO,"user:" + user.toJsonString());
            log.log(Level.INFO, "user?{0}", request.isUserInRole("user"));
            log.log(Level.INFO, "admin?{0}", request.isUserInRole("admin"));

            FacesContext facesContext = FacesContext.getCurrentInstance();
            
            facesContext.getApplication().getNavigationHandler().handleNavigation(facesContext, null, outcome);

        } else {
            FacesMessage message;
            if (user != null) {
                message = new FacesMessage(FacesMessage.SEVERITY_ERROR,
                        "Login Failed!",
                        "Username '"
                                + username
                                + "' supplied wrong password.");
            } else {
                message = new FacesMessage(FacesMessage.SEVERITY_ERROR,
                        "Login Failed!",
                        "Username '"
                                + username
                                + "' does not exist.");
            }
            context.addMessage(null, message);
            
        }
    }

    private User getUser() {
        User userToGet = null;
        try {
            userToGet = userManager.getUserByUserName(username);
            Logger.getLogger(LoginBean.class.getName()).log(Level.INFO, "user:{0}", userToGet.toJsonString());
            return userToGet;

        } catch (NoResultException |  NullPointerException ex) {

            Logger.getLogger(LoginBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return userToGet;
    }

    /**
     * <p>
     * When invoked, it will invalidate the user's session and move them to the
     * homepage.</p>
     *
     * @return <code>home</code>
     */
    public String logout() {
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance().getExternalContext().getSession(false);
        if (session != null) {
            session.invalidate();
        }
        
        return "/index?faces-redirect=true";

    }

}

reeler/src/main/java/com/hkstlr/reeler/weblogger/weblogs/control/SelectItemBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hkstlr.reeler.weblogger.weblogs.control;


import java.text.DateFormatSymbols;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;
import java.util.TimeZone;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.inject.Named;
import javax.enterprise.context.ApplicationScoped;
import javax.faces.model.SelectItem;
import javax.inject.Inject;


/**
 *
 * @author henry.kastler
 */
@Named(value = "selectItemBean")
@ApplicationScoped
public class SelectItemBean {

    
    private SelectItem[] monthItems;    
    private SelectItem[] yearItems;
    private SelectItem[] weblogCategoryItems;
    private SelectItem[] hourItems;
    private SelectItem[] minuteItems;
    private SelectItem[] secondItems;
    private SelectItem[] commentDaysItems;
    private SelectItem[] localeItems;

    @Inject
    private Logger log;
  
    /**
     * Creates a new instance of SelectItemBean
     */
    public SelectItemBean() {
        //constructor
    }
    
    @PostConstruct
    protected void init(){
        monthItems = getMonthSelectItems();
        yearItems = getYearSelectItems();
        hourItems = getHourSelectItems();
        minuteItems = getMinuteSelectItems();
        secondItems = getSecondSelectItems();
        commentDaysItems = getCommentDaysSelectItems();
        localeItems = getLocaleItems();
    }
    
    
    public SelectItem[] getCommentDaysItems() {
        return commentDaysItems;
    }

    public void setCommentDaysItems(SelectItem[] commentDaysItems) {
        this.commentDaysItems = commentDaysItems;
    }
    
    public SelectItem[] getMonthItems() {
        return monthItems;
    }

    public void setMonthItems(SelectItem[] monthItems) {
        this.monthItems = monthItems;
    }

    public SelectItem[] getYearItems() {
        return yearItems;
    }

    public void setYearItems(SelectItem[] yearItems) {
        this.yearItems = yearItems;
    }

    public SelectItem[] getWeblogCategoryItems() {
        return weblogCategoryItems;
    }

    public void setWeblogCategoryItems(SelectItem[] weblogCategoryItems) {
        this.weblogCategoryItems = weblogCategoryItems;
    }

    public SelectItem[] getHourItems() {
        return hourItems;
    }

    public void setHourItems(SelectItem[] hourItems) {
        this.hourItems = hourItems;
    }

    public SelectItem[] getMinuteItems() {
        return minuteItems;
    }

    public void setMinuteItems(SelectItem[] minuteItems) {
        this.minuteItems = minuteItems;
    }

    public SelectItem[] getSecondItems() {
        return secondItems;
    }

    public void setSecondItems(SelectItem[] secondItems) {
        this.secondItems = secondItems;
    }
    
    

    private SelectItem[] getMonthSelectItems() {
        SelectItem[] items = new SelectItem[12];
        
        for(int i=0; i<=11; i++){
            
            String strMonth = Integer.toString(i+1);
            if(strMonth.length()==1){
                strMonth= "0"+strMonth;
            }
            items[i] = new SelectItem(i+1,strMonth);
        }
        
        return items;
    }
    
    public String getMonth(int month) {
        return new DateFormatSymbols().getMonths()[month-1];
    }
    
    private SelectItem[] getYearSelectItems() {
        int currentYear;
        currentYear = Calendar.getInstance().get(Calendar.YEAR);
        
        int yearsToAppear = 10;
        SelectItem[] items = new SelectItem[yearsToAppear];
        int counter = 0;
        for(int i=currentYear; i<currentYear+yearsToAppear; i++){
            items[counter] = new SelectItem(i,Integer.toString(i));
            counter++;
        }
        
        return items;
    }
    
    
    private SelectItem[] getHourSelectItems() {
              
        SelectItem[] items = new SelectItem[24];
       
        for(int i=0; i<24; i++){
            items[i] = new SelectItem(i,Integer.toString(i));
           
        }
        
        return items;
    }
    
    private SelectItem[] getMinuteSelectItems() {
              
        SelectItem[] items = new SelectItem[60];
        int counter = 0;
        for(int i=0; i<60; i++){
            items[counter] = new SelectItem(i,Integer.toString(i));
            counter++;
        }
        
        return items;
    }
    
    private SelectItem[] getSecondSelectItems() {
        SelectItem[] items = new SelectItem[60];
        int counter = 0;
        for(int i=0; i<60; i++){
            items[counter] = new SelectItem(i,Integer.toString(i));
            counter++;
        }
        
        return items;
    }
    
    private SelectItem[] getCommentDaysSelectItems() {
        String dayLabel = "days";
       
        SelectItem[] items = new SelectItem[7];
        SelectItem item = new SelectItem();
        item.setValue(0);
        item.setLabel("unlimited days");
        items[0] = item;
        
        item = new SelectItem();
        item.setValue(3);
        item.setLabel("3 ".concat(dayLabel));
        items[1] = item;
        
        item = new SelectItem();
        item.setValue(7);
        item.setLabel("7 ".concat(dayLabel));
        items[2] = item;
        
        item = new SelectItem();
        item.setValue(14);
        item.setLabel("14 ".concat(dayLabel));
        items[3] = item;
        
        item = new SelectItem();
        item.setValue(30);
        item.setLabel("30 ".concat(dayLabel));
        items[4] = item;
        
        item = new SelectItem();
        item.setValue(60);
        item.setLabel("60 ".concat(dayLabel));
        items[5] = item;
        
        item = new SelectItem();
        item.setValue(90);
        item.setLabel("90 ".concat(dayLabel));
        items[6] = item;
        
        return items;
    }
    
    
    
    public SelectItem[] getLocaleItems() {
       
       Locale[] locales = Calendar.getAvailableLocales();       
       List<SelectItem> ftLocale = new ArrayList<>();        
       for (Locale locale : locales) { 
            if(locale.getDisplayCountry().length() > 0){
                ftLocale.add(new SelectItem(locale.toString(),locale.getDisplayCountry()) );
            }
       }              
               
       
        Comparator<SelectItem> localeNameSort = (SelectItem si1, SelectItem si2) 
                -> si1.getLabel().substring(0,1).compareTo(si2.getLabel().substring(0,1));
        
        Collections.sort(ftLocale,localeNameSort);
       
        return ftLocale.toArray(new SelectItem[ftLocale.size()]);
    }
    
     public SelectItem[] getTimeZoneItems() {
       
       String[] timeZones = TimeZone.getAvailableIDs();
       List<SelectItem> ftZones = new ArrayList<>();        
       for (String tz : timeZones) { 
           ftZones.add(new SelectItem(tz,tz) );
       }              
        
       Comparator<SelectItem> timeZoneNameSort = (SelectItem si1, SelectItem si2) 
                -> si1.getLabel().substring(0,1).compareTo(si2.getLabel().substring(0,1));
        
        Collections.sort(ftZones,timeZoneNameSort);
       
        return ftZones.toArray(new SelectItem[ftZones.size()]);
    }
     
     
}

reeler/src/main/webapp/weblogger/reeler-ui/user/profile/blank.xhtml
<span></span>

reeler/src/main/webapp/weblogger/reeler-ui/user/profile/index.xhtml
<ui:composition template="/WEB-INF/weblogger/templates/reeler-ui/pageContentTemplate.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:jsf="http://xmlns.jcp.org/jsf">

    <ui:define name="title">
        <h:outputText value="Edit Profile"></h:outputText>            
    </ui:define>

    <ui:define name="head">

    </ui:define>

    <ui:define name="navigation">

    </ui:define>
    <ui:define name="content">
        <f:view>
            <ui:include src="profile-form.xhtml">
                <ui:param name="formTitle" value="Edit Profile"/>
                <ui:param name="bean" value="#{userAdminBean}"/>
                <ui:param name="isAdmin" value="#{false}"/>
            </ui:include>
        </f:view>
    </ui:define>
    <ui:define name="sideNav">
       
    </ui:define>

    <ui:define name="postBody">

    </ui:define>

</ui:composition>

reeler/src/main/webapp/weblogger/reeler-ui/user/profile/profile-form.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:jsf="http://xmlns.jcp.org/jsf">



    <form jsfc="h:form" jsf:id="profile" name="profile" prependId="false">

        <div class="formdiv my-4">
            <h2>
                <h:outputText value="#{formTitle}"/>
            </h2>
            <h:messages
                layout="table"
                infoClass="table alert alert-success"
                errorClass="table alert alert-danger"/>
            <div class="form-group #{userName.isValid()? '' : 'has-error'}">
                <label jsf:for="userName" class="control-label #{userName.isValid()? '' : 'has-error'}" >Username</label>
                <input type="text"
                       class="form-control #{userName.isValid()? '' : 'has-error'}"
                       binding="#{userName}"
                       jsfc="h:inputText"
                       id="userName" 
                       value="#{bean.user.userName}" 
                       readonly="#{param.action eq 'edit' ? 'true':'false'}"
                       />
                <h:message for="userName" errorClass="control-label has-error"/>
                <span class="help-block" jsfc="h:panelGroup" rendered="#{!isAdmin} or #{param.action eq 'edit'}">
                    Usernames can't be changed.
                </span>
                <span class="help-block" jsfc="h:panelGroup" rendered="#{isAdmin}">
                    A short one-word username for the user account. 
                    Please limit it to simple ASCII alphanumeric characters (a-z, A-Z and 0-9), 
                    and do not use HTML
                </span>
            </div>

            <div class="form-group">
                <label jsf:for="screenName" class="control-label">Screen Name</label>
                <input type="text"
                       class="form-control"
                       jsf:id="screenName" 
                       jsf:value="#{bean.user.screenName}"/>

                <span class="help-block" jsfc="h:panelGroup" rendered="#{!isAdmin}">
                    Your desired screen name (with no HTML). This is is what will be displayed 
                    in your weblog and on weblog entries that you write.
                </span>

            </div>

            <div class="form-group">
                <label jsf:for="fullName" class="control-label">Full Name</label>
                <input type="text"
                       class="form-control"
                       jsf:id="fullName"
                       jsf:value="#{bean.user.fullName}"/>

                <span class="help-block" jsfc="h:panelGroup" rendered="#{!isAdmin}">
                    Your full name (with no HTML), first and last. 
                    Some weblog themes will display this instead of (or in addition to) your screenname.
                </span>

            </div>

            <div class="form-group">
                <label jsf:for="emailAddress" class="control-label">Email</label>
                <input type="text" 
                       class="form-control"
                       jsf:id="emailAddress" 
                       jsf:value="#{bean.user.emailAddress}"/>

                <span class="help-block" jsfc="h:panelGroup" rendered="#{!isAdmin}">
                    Please enter valid email address, the site administrator may disable your account 
                    if he/she cannot reach you via email.</span>

            </div>


            <div class="form-group">
                <label jsf:for="passwordText" class="control-label">Password</label>
                <h:inputSecret 
                    class="form-control"
                    id="passwordText"
                    binding="#{passwordComponent}"/>
                <h:message for="passwordText"/>
                <span class="help-block" jsfc="h:panelGroup" rendered="#{!isAdmin}">
                    Your password.  Fill in only if you wish to change it.
                </span>

            </div>

            <div class="form-group">
                <label jsf:for="passwordConfirm" class="control-label">Password (Confirm)</label>
                <h:inputSecret 
                    class="form-control"
                    id="passwordConfirm"
                    required="#{not empty passwordText.value}">
                    <f:validator validatorId="confirmPasswordValidator"/>
                    <f:attribute name="passwordComponent" value="#{passwordComponent}"/>
                </h:inputSecret>
                <h:message for="passwordConfirm"
                           errorClass="control-label has-error"/>
                <span class="help-block" jsfc="h:panelGroup" rendered="#{!isAdmin}">
                    Confirm your password.
                </span>
            </div>

            <div class="form-group">
                <label jsf:for="locale" >Locale</label>

                <select
                    id="locale"
                    name="locale"
                    jsfc="h:selectOneMenu"
                    title="Locale" 
                    class="form-control" 
                    value="#{bean.user.locale}"
                    required="true">
                    <option jsfc="f:selectItems" 
                            value="#{selectItemBean.localeItems}" 
                            var="locale" 
                            itemValue="#{locale.value}"
                            itemLabel="#{locale.label}" />

                </select>
                <h:message for="locale"/>
                <span class="help-block" jsfc="h:panelGroup" rendered="#{!isAdmin}">
                    Your preferred locale
                </span>
            </div>

            <div class="form-group">
                <label jsf:for="timeZone" >Timezone</label>
                <select
                    id="timeZone"
                    name="timeZone"
                    jsfc="h:selectOneMenu"
                    title="Time Zone" 
                    class="form-control" 
                    value="#{bean.user.timeZone}"
                    required="true">
                    <option jsfc="f:selectItems" 
                            value="#{selectItemBean.timeZoneItems}" 
                            var="tz" 
                            itemValue="#{tz.value}"
                            itemLabel="#{tz.label}" />

                </select>
                <h:message for="timeZone" />
                <span class="help-block" jsfc="h:panelGroup" rendered="#{!isAdmin}">
                    The timezone to be used for entry and display of this weblog.
                </span>
            </div>

            <div
                jsfc="h:panelGroup" 
                layout="block"
                rendered="#{isAdmin}">
                <div class="form-group">
                    <label jsf:for="isEnabled">
                        <h:selectBooleanCheckbox id="isEnabled" 
                                                 value="#{bean.user.isEnabled}"/>
                        Enabled
                    </label>
                </div>
                <div class="form-group">
                    <label jsf:for="isAdministrator">
                        <h:selectBooleanCheckbox id="isAdministrator"/>
                        Administrator
                    </label>
                </div>
            </div>
            

            <input type="hidden" 
                   jsfc="h:inputHidden" 
                   name="id"
                   rendered="#{bean.id ne null}"
                   value="#{bean.id ne null ? id : ''}"/>
            <input type="hidden" name="action" value="#{bean.action}"/>
        </div>

        <br />
        <input jsfc="h:commandButton"
               type="submit" 
               id="profile_save" 
               value="Save User" 
               class="btn btn-primary"
               action="#{bean.createUser()}"
               rendered="#{bean.action eq 'create'}"/>

        <input jsfc="h:commandButton"
               type="submit" 
               id="profile_edit" 
               value="Edit User" 
               class="btn btn-primary"
               action="#{bean.updateUser()}"
               rendered="#{bean.action eq 'edit'}"/>

        <input type="button" 
               value="#{messages._cancel}"
               onclick="window.location.href = '#{request.contextPath}#{bean.pageHome}'"
               class="btn btn-secondary"/>

    </form>
</ui:composition>